spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.132.138:3306/tx-manager?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: minghaozhi
#    ##  Hikari 连接池配置
#    hikari:
#      ## 最小空闲连接数量
#      minimum-idle: 5
#      ## 空闲连接存活最大时间，默认600000（10分钟）
#      idle-timeout: 180000
#      ## 连接池最大连接数，默认是10
#      maximum-pool-size: 10
#      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
#      auto-commit: true
#      ## 连接池母子
#      pool-name: MyHikariCP
#      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
#      max-lifetime: 1800000
#      ## 数据库连接超时时间,默认30秒，即30000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1
  redis:
    host: 47.98.132.138
    port: 6379
    password: minghaozhi
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    loadbalancer:
      retry:
        enabled: true
tx-lcn:
  logger:
    enabled: true
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://47.98.132.138:3306/tx_logger?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: minghaozhi
  manager:
    admin-key: admin
    dtx-time: 15000